export const Gents={
    title:"Gents Fashions",
    image1:"MensCollection/1.jpeg",
    image2:"MensCollection/2.jpeg",
    image3:"MensCollection/3.jpeg",
    image4:"MensCollection/4.jpeg",
    image5:"MensCollection/5.jpeg",
    image6:"MensCollection/6.jpg",
    image7:"MensCollection/7.jpg",
    image8:"MensCollection/8.jpg",
    price1:"559 INR",
    price2:"659 INR",
    price3:"759 INR",
    price4:"859 INR",
    price5:"959 INR",
    price6:"1059 INR",
    price7:"1159 INR",
    price8:"1259 INR",
}

export const Ladies={
    title:"Ladies Fashions",
    image1:"WomenCollections/1.jpeg",
    image2:"WomenCollections/2.jpeg",
    image3:"WomenCollections/3.jpeg",
    image4:"WomenCollections/4.jpeg",
    image5:"WomenCollections/5.jpeg",
    image6:"WomenCollections/6.jpeg",
    image7:"WomenCollections/7.jpeg",
    image8:"WomenCollections/8.jpg",
    price1:"559 INR",
    price2:"659 INR",
    price3:"759 INR",
    price4:"859 INR",
    price5:"959 INR",
    price6:"1059 INR",
    price7:"1159 INR",
    price8:"1259 INR",
}

